paths:
  logo:   'loldesign_publisher/logo.svg'
  logout: 'javascript://'

  menu_links:
    users:   
      name: 'Usuários'
      path: users_path
    recipes:
      name: 'Receitas'
    schedules: 
      name: 'Agenda / Cursos'

page_title: 'Loldesign Publisher | Dummy App'