paths:
  logo:   'loldesign_publisher/logo.svg'
  logout: 'javascript://'

  menu_links:
    banners:   
      name: 'Banner Home'
      path: users_path
    recipes:
      name: 'Receitas'
    schedules: 
      name: 'Agenda / Cursos'
