# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386c8ec81d1f8f65ee42d59bf9c175e0a4fef3ba0c538289cc2b301390da947f989e03f3b98a8bd9ab1de10d8cf0c59cabfd9e832a4adffa6c474c06fd6f2ef6

test:
  secret_key_base: 7419cafff5c1ab905106f56e3fea3d7b4b514391d296087c7dbb0d7a31c71f1cf718c7f23cbff32a768dbbb1d6cf0f87387aa28940161caa7e287be2348fb3d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
