paths:
  logo:   'loldesign_publisher/logo.png'
  logout: 'javadcript://'

  menu_links:
    banners:   
      name:'Banner Home'
      path: 'javascript://'
    recipes:
      name: 'Receitas'
      path: 'javascript://'
    schedules: 
      name: 'Agenda / Cursos'
      path: 'javascript://'